package com.fadhlalhafizh.submissionjetpackcompose.model

import com.fadhlalhafizh.submissionjetpackcompose.R

object PremierLeagueClubsData {
    val Epl = listOf(
        PremierLeagueClubs(
            id = 0,
            image = R.drawable.arsenal,
            name = "Arsenal",
            nickname = "The Gunners",
            stadium = "Emirates Stadium",
            location = "London",
            description = "Arsenal is a professional football club based in Islington, London, England that plays in the Premier League, the top flight of English football. The club has won 13 league titles, a record 14 FA Cups, two League Cups, 16 FA Community Shields, the League Centenary Trophy, one European Cup Winners' Cup, and one Inter-Cities Fairs Cup.",
            manager = "Mikel Arteta",
            captain = "Martin Ødegaard",
        ),
        PremierLeagueClubs(
            id = 1,
            image = R.drawable.av,
            name = "Aston Villa",
            nickname = "Villans",
            stadium = "Villa Park",
            location = "Birmingham",
            description = "Aston Villa Football Club is an English professional football club based in Aston, Birmingham. The club competes in the Premier League, the top tier of the English football league system. Founded in 1874, they have played at their home ground, Villa Park, since 1897. Aston Villa were one of the founder members of the Football League in 1888 and of the Premier League in 1992.",
            manager = "Unai Emery",
            captain = "Tyrone Mings",
        ),
        PremierLeagueClubs(
            id = 2,
            image = R.drawable.bournemouth,
            name = "Bournemouth",
            nickname = "The Cherries",
            stadium = "Dean Court",
            location = "Bournemouth",
            description = "AFC Bournemouth is a professional association football club based in Kings Park, Boscombe, a suburb of Bournemouth, Dorset, that plays in the Premier League, the top tier of the English football league system. Formed in 1899 as Boscombe St. John's Institute F.C., the club adopted their current name in 1972. Nicknamed The Cherries, since 1910 Bournemouth have played their home games at Dean Court.",
            manager = "Gary O'Neil",
            captain = "Lloyd Kelly",
        ),
        PremierLeagueClubs(
            id = 3,
            image = R.drawable.brentford,
            name = "Brentford",
            nickname = "The Bees",
            stadium = "Brentford Community Stadium",
            location = "London",
            description = "Brentford Football Club is a professional football club based in Brentford, Greater London, England. The club competes in the Premier League, the top tier of English football. The club was founded in 1889 and played home matches at Griffin Park from 1904 before moving to Brentford Community Stadium in 2020.",
            manager = "Thomas Frank",
            captain = "Pontus Jansson",
        ),
        PremierLeagueClubs(
            id = 4,
            image = R.drawable.brighton,
            name = "Brighton & Hove Albion",
            nickname = "The Seagulls",
            stadium = "Falmer Stadium",
            location = "Brighton",
            description = "Brighton & Hove Albion Football Club is an English professional football club based in the city of Brighton and Hove, East Sussex, that competes in the Premier League, the top tier of the English football league system. The club was formed in 1901 and played their home games at the Goldstone Ground in Hove from 1902 until 1997, when they moved to the Falmer Stadium, currently known for sponsorship purposes as the American Express Community Stadium, in Falmer, Brighton.",
            manager = "Roberto De Zerbi",
            captain = "Lewis Dunk",
        ),
        PremierLeagueClubs(
            id = 5,
            image = R.drawable.chelsea,
            name = "Chelsea",
            nickname = "The Blues",
            stadium = "Stamford Bridge",
            location = "London",
            description = "Chelsea Football Club is an English professional football club based in Fulham, London. Founded in 1905, the club competes in the Premier League, the top division of English football. Chelsea are among England's most successful clubs, having won over thirty competitive honours, including six league titles and six European trophies.",
            manager = "Mauricio Pochettino",
            captain = "Reece James",
        ),
        PremierLeagueClubs(
            id = 6,
            image = R.drawable.cp,
            name = "Crystal Palace",
            nickname = "The Eagles",
            stadium = "Selhurst Park",
            location = "London",
            description = "Crystal Palace Football Club is a professional football club based in Selhurst, South London, England, who currently compete in the Premier League, the highest level of English football. Although their official founding date is 1905, the club claim to be a continuation of the original amateur Crystal Palace football club formed in 1861, as both were owned by the same Crystal Palace Company.",
            manager = "Roy Hodgson",
            captain = "Joel Ward",
        ),
        PremierLeagueClubs(
            id = 7,
            image = R.drawable.everton,
            name = "Everton",
            nickname = "The Toffees",
            stadium = "Goodison Park",
            location = "Liverpool",
            description = "Everton Football Club is an English professional football club based in Liverpool that competes in the Premier League, the top tier of English football. The club has competed in the top division for a record 117 seasons, missing only four top-flight seasons since the creation of the Football League, of which it was a founding member. Everton is the second-longest continuous serving club in English top flight football and has won nine League Championships, five FA Cups, one UEFA Cup Winners Cup and nine Charity Shields.",
            manager = "Sean Dyche",
            captain = "Séamus Coleman",
        ),
        PremierLeagueClubs(
            id = 8,
            image = R.drawable.fulham,
            name = "Fulham",
            nickname = "The Cottagers",
            stadium = "Craven Cottage",
            location = "London",
            description = "Fulham Football Club is an English professional association football club based in Fulham, London. They currently compete in the Premier League, the highest level of the English football league system. Founded in 1879, they are London's oldest football club playing professionally. The club has spent 27 seasons in English football's top division, the majority of these in two spells during the 1960s and 2000s.",
            manager = "Marco Silva",
            captain = "Tom Cairney",
        ),
        PremierLeagueClubs(
            id = 9,
            image = R.drawable.leeds,
            name = "Leeds United",
            nickname = "The Whites",
            stadium = "Elland Road",
            location = "Leeds",
            description = "Leeds United Football Club is a professional football club in Leeds, West Yorkshire, England. The club was formed in 1919 following the disbanding of Leeds City F.C. by the Football League and took over their Elland Road stadium. They play in the Premier League, the first tier of English football.",
            manager = "Daniel Farke",
            captain = "Liam Cooper",
        ),
        PremierLeagueClubs(
            id = 10,
            image = R.drawable.leicester,
            name = "Leicester City",
            nickname = "The Foxes",
            stadium = "King Power Stadium",
            location = "Leicester",
            description = "Leicester City Football Club is an English professional football club based in Leicester in the East Midlands. The club competes in the Premier League, the top division of England's football league system, and plays its home matches at the King Power Stadium.",
            manager = "Enzo Maresca",
            captain = "-",
        ),
        PremierLeagueClubs(
            id = 11,
            image = R.drawable.liverpool,
            name = "Liverpool",
            nickname = "The Reds",
            stadium = "Anfield",
            location = "Liverpool",
            description = "Liverpool Football Club is a professional football club in Liverpool, England, that competes in the Premier League, the top tier of English football. Domestically, the club has won nineteen League titles, seven FA Cups, a record eight League Cups and fifteen FA Community Shields. In continental and international competitions, the club has won six European Cups, more than any other English club, three UEFA Cups, four UEFA Super Cups and one FIFA Club World Cup.",
            manager = "Jürgen Klopp",
            captain = "Virgil van Dijk",
        ),
        PremierLeagueClubs(
            id = 12,
            image = R.drawable.mancity,
            name = "Manchester City",
            nickname = "The Citizens",
            stadium = "Etihad Stadium",
            location = "Manchester",
            description = "Manchester City Football Club is an English football club based in Manchester that competes in the Premier League, the top flight of English football. Founded in 1880 as St. Mark's, it became Ardwick Association Football Club in 1887 and Manchester City in 1894. The club's home ground is the City of Manchester Stadium in east Manchester, to which it moved in 2003, having played at Maine Road since 1923.",
            manager = "Pep Guardiola",
            captain = "Kevin De Bruyne",
        ),
        PremierLeagueClubs(
            id = 13,
            image = R.drawable.manunited,
            name = "Manchester United",
            nickname = "The Red Devils",
            stadium = "Old Trafford",
            location = "Manchester",
            description = "Manchester United Football Club is a professional football club based in Old Trafford, Greater Manchester, England, that competes in the Premier League, the top flight of English football. Nicknamed 'the Red Devils', the club was founded as Newton Heath LYR Football Club in 1878, changed its name to Manchester United in 1902 and moved to its current stadium, Old Trafford, in 1910.",
            manager = "Erik ten Hag",
            captain = "Bruno Fernandes",
        ),
        PremierLeagueClubs(
            id = 14,
            image = R.drawable.newcastle,
            name = "Newcastle United",
            nickname = "The Magpies",
            stadium = "St James' Park",
            location = "Newcastle upon Tyne",
            description = "Newcastle United Football Club is an English professional football club based in Newcastle upon Tyne, Tyne and Wear, that plays in the Premier League, the top flight of English football. Founded in 1892 by the merger of Newcastle East End and Newcastle West End. The team plays its home matches at St. James' Park. Per the Taylor Report's requirement that all Premier League clubs have an all-seater stadium, the ground was adjusted in the mid-1990s and now has a capacity of 52,305.",
            manager = "Eddie Howe",
            captain = "Jamaal Lascelles",
        ),
        PremierLeagueClubs(
            id = 15,
            image = R.drawable.nf,
            name = "Nottingham Forest",
            nickname = "Forest",
            stadium = "City Ground",
            location = "West Bridgford",
            description = "Nottingham Forest Football Club is a professional football club based in West Bridgford, Nottinghamshire, England. They are currently playing in the EFL Championship, the second tier of the English football league system. The club was founded in 1865 and have played home matches at the City Ground since 1898. They compete in the East Midlands derby against rivals Derby County.",
            manager = "Steve Cooper",
            captain = "Joe Worrall",
        ),
        PremierLeagueClubs(
            id = 16,
            image = R.drawable.southampton,
            name = "Southampton",
            nickname = "The Saints",
            stadium = "St Mary's Stadium",
            location = "Southampton",
            description = "Southampton Football Club is an English professional football club based in Southampton, Hampshire, that competes in the EFL Championship, the second tier of English football. Its home ground since 2001 has been St Mary's Stadium, before which it was based at The Dell. The team play in red and white shirts. They have been nicknamed \"The Saints\" because of the club's beginnings as a church football team at St Mary's Church.",
            manager = "Russell Martin",
            captain = "Jack Stephens",
        ),
        PremierLeagueClubs(
            id = 17,
            image = R.drawable.spurs,
            name = "Tottenham Hotspur",
            nickname = "The Lilywhites",
            stadium = "Tottenham Hotspur Stadium",
            location = "London",
            description = "Tottenham Hotspur Football Club is a professional football club based in Tottenham, London, England, that competes in the Premier League, the highest tier of English football. The club was founded in 1882 by workers from Hotspur Cricket Club and was originally named Hotspur Football Club. Their first game was against a local team named the Radicals and ended in a draw. Hotspur soon became a member of the Football Association and played in the FA Cup for the first time in the 1884–85 season.",
            manager = "Ange Postecoglou",
            captain = "Son Heung-min",
        ),
        PremierLeagueClubs(
            id = 18,
            image = R.drawable.wh,
            name = "West Ham United",
            nickname = "The Hammers",
            stadium = "London Stadium",
            location = "London",
            description = "West Ham United Football Club is an English professional football club based in Stratford, East London that compete in the Premier League, the top tier of English football. The club plays at the London Stadium, having moved from their former home the Boleyn Ground in 2016. The club was founded in 1895 as Thames Ironworks and reformed in 1900 as West Ham United. They moved to the Boleyn Ground in 1904, which remained their home ground for more than a century.",
            manager = "David Moyes",
            captain = "Kurt Zouma",
        ),
        PremierLeagueClubs(
            id = 19,
            image = R.drawable.ww,
            name = "Wolverhampton Wanderers",
            nickname = "Wolves",
            stadium = "Molineux Stadium",
            location = "Wolverhampton",
            description = "Wolverhampton Wanderers Football Club is a professional association football club based in Wolverhampton, West Midlands, England. The club was formed as St. Luke's F.C. in 1877 by John Baynton and John Brodie after a group of pupils at St Luke's Church of England school in Blakenhall had been presented with a football by their headmaster Harry Barcroft. Two years later, they merged with local cricket and football club The Wanderers, to form Wolverhampton Wanderers F.C.",
            manager = "Julen Lopetegui",
            captain = "Max Kilman",
        )
    )
}